name: passbook_app
description: "A new Flutter premium ePassbook application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  onesignal_flutter: ^5.2.6
  google_fonts: ^6.2.1
  fl_chart: ^0.70.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
